<a href="https://colab.research.google.com/github/12rahulkumar/Machine_Learning/blob/master/Pandas_2nd_Class.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

titanic_train = pd.read_csv("https://gist.githubusercontent.com/michhar/2dfd2de0d4f8727f873422c5d959fff5/raw/ff414a1bcfcba32481e4d4e8db578e55872a2ca1/titanic.csv",
                           sep='\t')

titanic_train

PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
0              1         0       3  ...   7.2500   NaN         S
1              2         1       1  ...  71.2833   C85         C
2              3         1       3  ...   7.9250   NaN         S
3              4         1       1  ...  53.1000  C123         S
4              5         0       3  ...   8.0500   NaN         S
..           ...       ...     ...  ...      ...   ...       ...
151          152         1       1  ...  66.6000    C2         S
152          153         0       3  ...   8.0500   NaN         S
153          154         0       3  ...  14.5000   NaN         S
154          155         0       3  ...   7.3125   NaN         S
155          156         0       1  ...  61.3792   NaN         C

[156 rows x 12 columns]

In [2]:
titanic_train.tail(10)

PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
146          147         1       3  ...   7.7958   NaN         S
147          148         0       3  ...  34.3750   NaN         S
148          149         0       2  ...  26.0000    F2         S
149          150         0       2  ...  13.0000   NaN         S
150          151         0       2  ...  12.5250   NaN         S
151          152         1       1  ...  66.6000    C2         S
152          153         0       3  ...   8.0500   NaN         S
153          154         0       3  ...  14.5000   NaN         S
154          155         0       3  ...   7.3125   NaN         S
155          156         0       1  ...  61.3792   NaN         C

[10 rows x 12 columns]

In [3]:
titanic_train.head(10)

PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
0            1         0       3  ...   7.2500   NaN         S
1            2         1       1  ...  71.2833   C85         C
2            3         1       3  ...   7.9250   NaN         S
3            4         1       1  ...  53.1000  C123         S
4            5         0       3  ...   8.0500   NaN         S
5            6         0       3  ...   8.4583   NaN         Q
6            7         0       1  ...  51.8625   E46         S
7            8         0       3  ...  21.0750   NaN         S
8            9         1       3  ...  11.1333   NaN         S
9           10         1       2  ...  30.0708   NaN         C

[10 rows x 12 columns]

In [4]:
titanic_train.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [6]:
titanic_train.dtypes == "object"
a = titanic_train.dtypes[titanic_train.dtypes == "object"].index
a

Index(['Name', 'Sex', 'Ticket', 'Cabin', 'Embarked'], dtype='object')

In [10]:
list_col = titanic_train.dtypes[titanic_train.dtypes == "object"].index
titanic_train[list_col].describe()

Name   Sex  Ticket Cabin Embarked
count                      156   156     156    31      155
unique                     156     2     145    28        3
top     Barton, Mr. David John  male  349909   D26        S
freq                         1   100       2     2      110

In [9]:
titanic_train.dtypes[titanic_train.dtypes == "object"]

Name        object
Sex         object
Ticket      object
Cabin       object
Embarked    object
dtype: object

In [7]:
titanic_train[a].describe()

Name   Sex  Ticket Cabin Embarked
count                      156   156     156    31      155
unique                     156     2     145    28        3
top     Barton, Mr. David John  male  349909   D26        S
freq                         1   100       2     2      110

In [8]:
titanic_train.describe()

PassengerId    Survived      Pclass  ...       SibSp       Parch        Fare
count   156.000000  156.000000  156.000000  ...  156.000000  156.000000  156.000000
mean     78.500000    0.346154    2.423077  ...    0.615385    0.397436   28.109587
std      45.177428    0.477275    0.795459  ...    1.056235    0.870146   39.401047
min       1.000000    0.000000    1.000000  ...    0.000000    0.000000    6.750000
25%      39.750000    0.000000    2.000000  ...    0.000000    0.000000    8.003150
50%      78.500000    0.000000    3.000000  ...    0.000000    0.000000   14.454200
75%     117.250000    1.000000    3.000000  ...    1.000000    0.000000   30.371850
max     156.000000    1.000000    3.000000  ...    5.000000    5.000000  263.000000

[8 rows x 7 columns]

In [11]:
titanic_train[['Name','Sex','Age']]

Name     Sex   Age
0                              Braund, Mr. Owen Harris    male  22.0
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0
2                               Heikkinen, Miss. Laina  female  26.0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0
4                             Allen, Mr. William Henry    male  35.0
..                                                 ...     ...   ...
151                  Pears, Mrs. Thomas (Edith Wearne)  female  22.0
152                                   Meo, Mr. Alfonzo    male  55.5
153                    van Billiard, Mr. Austin Blyler    male  40.5
154                              Olsen, Mr. Ole Martin    male   NaN
155                        Williams, Mr. Charles Duane    male  51.0

[156 rows x 3 columns]

In [12]:
sorted(titanic_train["Name"])[5:10:2]# Check the first 15 sorted names

['Andersson, Mr. August Edvard ("Wennerstrom")',
 'Andrew, Mr. Edgardo Samuel',
 'Asplund, Mrs. Carl Oscar (Selma Augusta Emilia Johansson)']

In [13]:
titanic_train["Name"].describe()

count                        156
unique                       156
top       Barton, Mr. David John
freq                           1
Name: Name, dtype: object

In [14]:
titanic_train[["Ticket"]][4:9]

Ticket
4  373450
5  330877
6   17463
7  349909
8  347742

In [15]:
titanic_train["Ticket"].describe()
titanic_train.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [16]:
titanic_train["sudh"]="sdffs"
titanic_train.head()

PassengerId  Survived  Pclass  ... Cabin Embarked   sudh
0            1         0       3  ...   NaN        S  sdffs
1            2         1       1  ...   C85        C  sdffs
2            3         1       3  ...   NaN        S  sdffs
3            4         1       1  ...  C123        S  sdffs
4            5         0       3  ...   NaN        S  sdffs

[5 rows x 13 columns]

In [17]:
titanic_train["Cabin"][0:15]       # Check the first 15 tickets

0      NaN
1      C85
2      NaN
3     C123
4      NaN
5      NaN
6      E46
7      NaN
8      NaN
9      NaN
10      G6
11    C103
12     NaN
13     NaN
14     NaN
Name: Cabin, dtype: object

In [18]:
titanic_train["Survived"]

0      0
1      1
2      1
3      1
4      0
      ..
151    1
152    0
153    0
154    0
155    0
Name: Survived, Length: 156, dtype: int64

In [19]:
titanic_train.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked', 'sudh'],
      dtype='object')

In [20]:
new_Pclass = pd.Categorical(titanic_train["Pclass"])

new_Pclass

[3, 1, 3, 1, 3, ..., 1, 3, 3, 3, 1]
Length: 156
Categories (3, int64): [1, 2, 3]

In [21]:
new_Pclass = pd.Categorical(titanic_train["Pclass"])
new_Pclass

[3, 1, 3, 1, 3, ..., 1, 3, 3, 3, 1]
Length: 156
Categories (3, int64): [1, 2, 3]

In [23]:
titanic_train["Cabin"].unique()   # Check unique cabins

array([nan, 'C85', 'C123', 'E46', 'G6', 'C103', 'D56', 'A6',
       'C23 C25 C27', 'B78', 'D33', 'B30', 'C52', 'B28', 'C83', 'F33',
       'F G73', 'E31', 'A5', 'D10 D12', 'D26', 'C110', 'B58 B60', 'E101',
       'F E69', 'D47', 'B86', 'F2', 'C2'], dtype=object)

In [24]:
import numpy as np 
char_cabin = titanic_train["Cabin"].astype(str) # Convert data to str

new_Cabin = [cabin[0] for cabin in char_cabin] # Take first letter

new_Cabin = pd.Categorical(new_Cabin)
#new_Cabin
new_Cabin

[n, C, n, C, n, ..., C, n, n, n, n]
Length: 156
Categories (8, object): [A, B, C, D, E, F, G, n]

In [25]:
titanic_train["Cabin"] = new_Cabin
titanic_train.head()

PassengerId  Survived  Pclass  ... Cabin Embarked   sudh
0            1         0       3  ...     n        S  sdffs
1            2         1       1  ...     C        C  sdffs
2            3         1       3  ...     n        S  sdffs
3            4         1       1  ...     C        S  sdffs
4            5         0       3  ...     n        S  sdffs

[5 rows x 13 columns]

In [26]:
titanic_train["Age"].isnull() 

0      False
1      False
2      False
3      False
4      False
       ...  
151    False
152    False
153    False
154     True
155    False
Name: Age, Length: 156, dtype: bool

In [27]:
missing = np.where(titanic_train["Age"].isnull() == True)
missing

(array([  5,  17,  19,  26,  28,  29,  31,  32,  36,  42,  45,  46,  47,
         48,  55,  64,  65,  76,  77,  82,  87,  95, 101, 107, 109, 121,
        126, 128, 140, 154]),)

In [28]:
np.where(titanic_train["Fare"]==max(titanic_train["Fare"]))

(array([27, 88]),)

In [29]:
titanic_train.iloc[np.where(titanic_train["Fare"]==max(titanic_train["Fare"]))]

PassengerId  Survived  Pclass  ... Cabin Embarked   sudh
27           28         0       1  ...     C        S  sdffs
88           89         1       1  ...     C        S  sdffs

[2 rows x 13 columns]

In [30]:
np.where(titanic_train["Fare"]==max(titanic_train["Fare"]))

(array([27, 88]),)

In [31]:
len(missing[0])

30

In [32]:
titanic_train["Family"] = titanic_train["SibSp"] + titanic_train["Parch"]
titanic_train["Family"]
most_family = np.where(titanic_train["Family"] == max(titanic_train["Family"]))
most_family

(array([59, 71]),)

In [33]:
titanic_train["Family"] = titanic_train["SibSp"] + titanic_train["Parch"]

most_family = np.where(titanic_train["Family"] == max(titanic_train["Family"]))
most_family
titanic_train.iloc[most_family]

PassengerId  Survived  Pclass  ... Embarked   sudh  Family
59           60         0       3  ...        S  sdffs       7
71           72         0       3  ...        S  sdffs       7

[2 rows x 14 columns]

In [34]:
import numpy as np
import pandas as pd

labels = ['a','b','c']
my_data = [10,20,30]
arr = np.array(my_data)
d = {'a':10,'b':20,'c':30}

print ("Labels:", labels)
print("My data:", my_data)
print("Dictionary:", d)
pd.Series(my_data, index=labels)

Labels: ['a', 'b', 'c']
My data: [10, 20, 30]
Dictionary: {'a': 10, 'b': 20, 'c': 30}


a    10
b    20
c    30
dtype: int64

In [35]:
pd.Series(my_data, index=labels)

a    10
b    20
c    30
dtype: int64

In [36]:
print ("\nHolding numerical data\n",'-'*25, sep='')
print(pd.Series(arr)[1])



Holding numerical data
-------------------------
20


In [37]:
print ("\nHolding text labels\n",'-'*20, sep='')
print(pd.Series(labels))


Holding text labels
--------------------
0    a
1    b
2    c
dtype: object


In [38]:
d = {'a':"kjhk",'b':20,'c':30}
d.items
pd.DataFrame(d,index = ['a','b','c'])

a   b   c
a  kjhk  20  30
b  kjhk  20  30
c  kjhk  20  30

In [39]:
print ("\nHolding objects from a dictionary\n",'-'*40, sep='')
print(pd.Series([type, sum, max]))


Holding objects from a dictionary
----------------------------------------
0             <class 'type'>
1    <built-in function sum>
2    <built-in function max>
dtype: object


In [40]:
ser1 = pd.Series([1,2,3,4],index = [2,4,6,8])
ser2 = pd.Series([1,2,5,4],['CA', 'OR', 'NV', 'AZ'])
ser1

2    1
4    2
6    3
8    4
dtype: int64

In [41]:
ser1[0:3:2]


2    1
6    3
dtype: int64

In [44]:
print ("\nIndexing by number (positional value in the series)\n",'-'*52, sep='')
print("Value for CA in ser1:", ser1[0])
print("Value for AZ in ser1:", ser1[3])
print("Value for NV in ser2:", ser2[2])
ser1


Indexing by number (positional value in the series)
----------------------------------------------------


KeyError: ignored

In [43]:
print ("\nIndexing by a range\n",'-'*25, sep='')
print ("Value for OR, CO, and AZ in ser1:\n", ser1[0:3:2], sep='')


Indexing by a range
-------------------------
Value for OR, CO, and AZ in ser1:
2    1
6    3
dtype: int64


In [45]:
ser1 = pd.Series([1,2,3,4],['CA', 'OR', 'CO', 'CA'])
ser2 = pd.Series([1,2,5,4],['CA', 'NV', 'AZ','OR'])
ser3 = ser1+ser2
ser3

AZ    NaN
CA    2.0
CA    5.0
CO    NaN
NV    NaN
OR    6.0
dtype: float64

In [46]:
print ("\nAfter adding the two series, the result looks like this...\n",'-'*59, sep='')
print(ser3)
print("\nPython tries to add values where it finds common index name, and puts NaN where indices are missing\n")



After adding the two series, the result looks like this...
-----------------------------------------------------------
AZ    NaN
CA    2.0
CA    5.0
CO    NaN
NV    NaN
OR    6.0
dtype: float64

Python tries to add values where it finds common index name, and puts NaN where indices are missing



In [47]:
print ("\nThe idea works even for multiplication...\n",'-'*43, sep='')
print (ser1*ser2)


The idea works even for multiplication...
-------------------------------------------
AZ    NaN
CA    1.0
CA    4.0
CO    NaN
NV    NaN
OR    8.0
dtype: float64


In [48]:
from numpy.random import randn as rn
#np.random.seed(101)
matrix_data = rn(5,4)
row_labels = ['A','B','C','D','E']
column_headings = ['W','X','Y','Z']

df = pd.DataFrame(matrix_data,row_labels,column_headings)
#print("\nThe data frame looks like\n",'-'*45, sep='')
df

W         X         Y         Z
A -2.430187  1.095557  0.149170  0.180160
B  0.636486 -0.024126 -0.144837  0.343609
C  0.191058 -0.099165 -0.468208 -0.267668
D  0.739037  1.167716  0.220360 -0.257502
E  0.419092  1.809772  0.940226 -1.008353

In [49]:
df.iloc[2]

W    0.191058
X   -0.099165
Y   -0.468208
Z   -0.267668
Name: C, dtype: float64

In [50]:
print("\nType of the pair of columns: ", type(df[['X','Z']]), sep='')
print ("\nSo, for more than one column, the object turns into a DataFrame")


Type of the pair of columns: <class 'pandas.core.frame.DataFrame'>

So, for more than one column, the object turns into a DataFrame


In [51]:
print("\nThe 'X' column accessed by DOT method (NOT recommended)\n",'-'*55, sep='')
print(df["X"])


The 'X' column accessed by DOT method (NOT recommended)
-------------------------------------------------------
A    1.095557
B   -0.024126
C   -0.099165
D    1.167716
E    1.809772
Name: X, dtype: float64


In [52]:
print("\nA column is created by assigning it in relation to an existing column\n",'-'*75, sep='')
df['New'] = df['X']+df['Z']
df['New (Sum of X and Z)'] = df['X']+df['Z']
print(df)


A column is created by assigning it in relation to an existing column
---------------------------------------------------------------------------
          W         X         Y         Z       New  New (Sum of X and Z)
A -2.430187  1.095557  0.149170  0.180160  1.275717              1.275717
B  0.636486 -0.024126 -0.144837  0.343609  0.319482              0.319482
C  0.191058 -0.099165 -0.468208 -0.267668 -0.366832             -0.366832
D  0.739037  1.167716  0.220360 -0.257502  0.910213              0.910213
E  0.419092  1.809772  0.940226 -1.008353  0.801420              0.801420


In [53]:
df

W         X         Y         Z       New  New (Sum of X and Z)
A -2.430187  1.095557  0.149170  0.180160  1.275717              1.275717
B  0.636486 -0.024126 -0.144837  0.343609  0.319482              0.319482
C  0.191058 -0.099165 -0.468208 -0.267668 -0.366832             -0.366832
D  0.739037  1.167716  0.220360 -0.257502  0.910213              0.910213
E  0.419092  1.809772  0.940226 -1.008353  0.801420              0.801420

In [54]:
print("\nA column is dropped by using df.drop() method\n",'-'*55, sep=' ')
df.drop("C",inplace=True) # Notice the axis=1 option, axis = 0 is default, so one has to change it to 1


A column is dropped by using df.drop() method
 -------------------------------------------------------


In [55]:
df

W         X         Y         Z       New  New (Sum of X and Z)
A -2.430187  1.095557  0.149170  0.180160  1.275717              1.275717
B  0.636486 -0.024126 -0.144837  0.343609  0.319482              0.319482
D  0.739037  1.167716  0.220360 -0.257502  0.910213              0.910213
E  0.419092  1.809772  0.940226 -1.008353  0.801420              0.801420

In [56]:
df1=df.drop('A')
print("\nA row (index) is dropped by using df.drop() method and axis=0\n",'-'*65, sep='')
print(df1)


A row (index) is dropped by using df.drop() method and axis=0
-----------------------------------------------------------------
          W         X         Y         Z       New  New (Sum of X and Z)
B  0.636486 -0.024126 -0.144837  0.343609  0.319482              0.319482
D  0.739037  1.167716  0.220360 -0.257502  0.910213              0.910213
E  0.419092  1.809772  0.940226 -1.008353  0.801420              0.801420


In [57]:
print("\nAn in-place change can be done by making inplace=True in the drop method\n",'-'*75, sep='')
df.drop('New (Sum of X and Z)', axis=1, inplace=True)
print(df)


An in-place change can be done by making inplace=True in the drop method
---------------------------------------------------------------------------
          W         X         Y         Z       New
A -2.430187  1.095557  0.149170  0.180160  1.275717
B  0.636486 -0.024126 -0.144837  0.343609  0.319482
D  0.739037  1.167716  0.220360 -0.257502  0.910213
E  0.419092  1.809772  0.940226 -1.008353  0.801420


In [58]:
### Selecting/indexing Rows
#* Label-based 'loc' method
#* Index (numeric) 'iloc' method
df

W         X         Y         Z       New
A -2.430187  1.095557  0.149170  0.180160  1.275717
B  0.636486 -0.024126 -0.144837  0.343609  0.319482
D  0.739037  1.167716  0.220360 -0.257502  0.910213
E  0.419092  1.809772  0.940226 -1.008353  0.801420

In [59]:
print("\nLabel-based 'loc' method can be used for selecting row(s)\n",'-'*60, sep='')
print("\nSingle row\n")
print(df.iloc[3])


Label-based 'loc' method can be used for selecting row(s)
------------------------------------------------------------

Single row

W      0.419092
X      1.809772
Y      0.940226
Z     -1.008353
New    0.801420
Name: E, dtype: float64


In [60]:
print("\nMultiple rows\n")
print(df.loc[['B','C']])


Multiple rows



KeyError: ignored

In [61]:
print("\nIndex position based 'iloc' method can be used for selecting row(s)\n",'-'*70, sep='')
print("\nSingle row\n")
print(df.iloc[2])


Index position based 'iloc' method can be used for selecting row(s)
----------------------------------------------------------------------

Single row

W      0.739037
X      1.167716
Y      0.220360
Z     -0.257502
New    0.910213
Name: D, dtype: float64


In [62]:
print("\nMultiple rows\n")
print(df.iloc[[1,2]])


Multiple rows

          W         X         Y         Z       New
B  0.636486 -0.024126 -0.144837  0.343609  0.319482
D  0.739037  1.167716  0.220360 -0.257502  0.910213
